-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- Create the todos table
create table todos (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  title text not null,
  description text,
  completed boolean default false,
  priority text default 'Medium',
  due_datetime timestamptz,
  user_id uuid references auth.users not null default auth.uid()
);

-- Enable Row Level Security (RLS)
alter table todos enable row level security;

-- Create Policies
create policy "Users can view their own todos"
  on todos for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own todos"
  on todos for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own todos"
  on todos for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own todos"
  on todos for delete
  using ( auth.uid() = user_id );

