-- 1. For Feature #11: User Profiles (Best Practice)
-- Allows storing extra user data like separate display names, avatars, or settings
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamptz,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  constraint username_length check (char_length(username) >= 3)
);

-- Enable RLS for Profiles
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Optional: specific trigger to create profile on signup (or handle in app)

-- 2. For Feature #12: Tags/Categories
-- Simplest approach: Add a text array column to the existing todos table
alter table public.todos 
add column tags text[] default '{}';

-- 3. For Feature #13: Subtasks
-- Create a separate table linked to the parent todo
create table public.subtasks (
  id bigint generated by default as identity primary key,
  todo_id bigint references public.todos on delete cascade not null,
  title text not null,
  completed boolean default false,
  created_at timestamptz default now(),
  user_id uuid references auth.users not null default auth.uid()
);

-- Enable RLS for Subtasks
alter table public.subtasks enable row level security;

create policy "Users can CRUD their own subtasks"
  on subtasks for all
  using ( auth.uid() = user_id );

-- 4. For Feature #14: Drag & Drop Sorting
-- Add a position column (float allows inserting between items easily)
alter table public.todos
add column position double precision default 0;

-- 5. For Subtask Drag & Drop
-- Add 'position' column to subtasks for ordering
alter table public.subtasks
add column if not exists position double precision default 0;

-- Optional: Initialize positions for existing subtasks
with indexed_subtasks as (
  select id, row_number() over (partition by todo_id order by created_at) as rn
  from public.subtasks
)
update public.subtasks s
set position = i.rn * 1000
from indexed_subtasks i
where s.id = i.id;
